package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * AsignacionHasFormularioCovid generated by hbm2java
 */
public class AsignacionHasFormularioCovid  implements java.io.Serializable {


     private AsignacionHasFormularioCovidId id;

    public AsignacionHasFormularioCovid() {
    }

    public AsignacionHasFormularioCovid(AsignacionHasFormularioCovidId id) {
       this.id = id;
    }
   
    public AsignacionHasFormularioCovidId getId() {
        return this.id;
    }
    
    public void setId(AsignacionHasFormularioCovidId id) {
        this.id = id;
    }




}


