package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * AsignacionHasFormularioCovidId generated by hbm2java
 */
public class AsignacionHasFormularioCovidId  implements java.io.Serializable {


     private int asignacionIdAsignacion;
     private int formularioCovidIdFc;

    public AsignacionHasFormularioCovidId() {
    }

    public AsignacionHasFormularioCovidId(int asignacionIdAsignacion, int formularioCovidIdFc) {
       this.asignacionIdAsignacion = asignacionIdAsignacion;
       this.formularioCovidIdFc = formularioCovidIdFc;
    }
   
    public int getAsignacionIdAsignacion() {
        return this.asignacionIdAsignacion;
    }
    
    public void setAsignacionIdAsignacion(int asignacionIdAsignacion) {
        this.asignacionIdAsignacion = asignacionIdAsignacion;
    }
    public int getFormularioCovidIdFc() {
        return this.formularioCovidIdFc;
    }
    
    public void setFormularioCovidIdFc(int formularioCovidIdFc) {
        this.formularioCovidIdFc = formularioCovidIdFc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsignacionHasFormularioCovidId) ) return false;
		 AsignacionHasFormularioCovidId castOther = ( AsignacionHasFormularioCovidId ) other; 
         
		 return (this.getAsignacionIdAsignacion()==castOther.getAsignacionIdAsignacion())
 && (this.getFormularioCovidIdFc()==castOther.getFormularioCovidIdFc());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAsignacionIdAsignacion();
         result = 37 * result + this.getFormularioCovidIdFc();
         return result;
   }   


}


