package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asignacion generated by hbm2java
 */
public class Asignacion  implements java.io.Serializable {


     private int idAsignacion;
     private Date fechaAsiganacion;
     private int grupoIdGrupo;
     private int laboratorioIdLaboratorio;

    public Asignacion() {
    }

	
    public Asignacion(int idAsignacion, int grupoIdGrupo, int laboratorioIdLaboratorio) {
        this.idAsignacion = idAsignacion;
        this.grupoIdGrupo = grupoIdGrupo;
        this.laboratorioIdLaboratorio = laboratorioIdLaboratorio;
    }
    public Asignacion(int idAsignacion, Date fechaAsiganacion, int grupoIdGrupo, int laboratorioIdLaboratorio) {
       this.idAsignacion = idAsignacion;
       this.fechaAsiganacion = fechaAsiganacion;
       this.grupoIdGrupo = grupoIdGrupo;
       this.laboratorioIdLaboratorio = laboratorioIdLaboratorio;
    }
   
    public int getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(int idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public Date getFechaAsiganacion() {
        return this.fechaAsiganacion;
    }
    
    public void setFechaAsiganacion(Date fechaAsiganacion) {
        this.fechaAsiganacion = fechaAsiganacion;
    }
    public int getGrupoIdGrupo() {
        return this.grupoIdGrupo;
    }
    
    public void setGrupoIdGrupo(int grupoIdGrupo) {
        this.grupoIdGrupo = grupoIdGrupo;
    }
    public int getLaboratorioIdLaboratorio() {
        return this.laboratorioIdLaboratorio;
    }
    
    public void setLaboratorioIdLaboratorio(int laboratorioIdLaboratorio) {
        this.laboratorioIdLaboratorio = laboratorioIdLaboratorio;
    }

}


