package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int idCarrera;
     private String nombreCarrera;
     private String facultad;
     private int usuarioIdUsuario;

    public Carrera() {
    }

	
    public Carrera(int idCarrera, int usuarioIdUsuario) {
        this.idCarrera = idCarrera;
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public Carrera(int idCarrera, String nombreCarrera, String facultad, int usuarioIdUsuario) {
       this.idCarrera = idCarrera;
       this.nombreCarrera = nombreCarrera;
       this.facultad = facultad;
       this.usuarioIdUsuario = usuarioIdUsuario;
    }
   
    public int getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(int idCarrera) {
        this.idCarrera = idCarrera;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }




}


