package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FormularioCovid generated by hbm2java
 */
public class FormularioCovid  implements java.io.Serializable {


     private int idFc;
     private Byte estadoCovid;
     private Date fechaVacunacion;

    public FormularioCovid() {
    }

	
    public FormularioCovid(int idFc) {
        this.idFc = idFc;
    }
    public FormularioCovid(int idFc, Byte estadoCovid, Date fechaVacunacion) {
       this.idFc = idFc;
       this.estadoCovid = estadoCovid;
       this.fechaVacunacion = fechaVacunacion;
    }
   
    public int getIdFc() {
        return this.idFc;
    }
    
    public void setIdFc(int idFc) {
        this.idFc = idFc;
    }
    public Byte getEstadoCovid() {
        return this.estadoCovid;
    }
    
    public void setEstadoCovid(Byte estadoCovid) {
        this.estadoCovid = estadoCovid;
    }
    public Date getFechaVacunacion() {
        return this.fechaVacunacion;
    }
    
    public void setFechaVacunacion(Date fechaVacunacion) {
        this.fechaVacunacion = fechaVacunacion;
    }




}


