package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int idGrupo;
     private String nombreGrupo;
     private Integer cantidadIntegrantes;
     private String responsable;

    public Grupo() {
    }

	
    public Grupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Grupo(int idGrupo, String nombreGrupo, Integer cantidadIntegrantes, String responsable) {
       this.idGrupo = idGrupo;
       this.nombreGrupo = nombreGrupo;
       this.cantidadIntegrantes = cantidadIntegrantes;
       this.responsable = responsable;
    }
   
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public Integer getCantidadIntegrantes() {
        return this.cantidadIntegrantes;
    }
    
    public void setCantidadIntegrantes(Integer cantidadIntegrantes) {
        this.cantidadIntegrantes = cantidadIntegrantes;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }




}


