package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private int idHorario;
     private String horarioInicial;
     private String horarioFinal;
     private String diasHabilitados;

    public Horario() {
    }

	
    public Horario(int idHorario) {
        this.idHorario = idHorario;
    }
    public Horario(int idHorario, String horarioInicial, String horarioFinal, String diasHabilitados) {
       this.idHorario = idHorario;
       this.horarioInicial = horarioInicial;
       this.horarioFinal = horarioFinal;
       this.diasHabilitados = diasHabilitados;
    }
   
    public int getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }
    public String getHorarioInicial() {
        return this.horarioInicial;
    }
    
    public void setHorarioInicial(String horarioInicial) {
        this.horarioInicial = horarioInicial;
    }
    public String getHorarioFinal() {
        return this.horarioFinal;
    }
    
    public void setHorarioFinal(String horarioFinal) {
        this.horarioFinal = horarioFinal;
    }
    public String getDiasHabilitados() {
        return this.diasHabilitados;
    }
    
    public void setDiasHabilitados(String diasHabilitados) {
        this.diasHabilitados = diasHabilitados;
    }




}


