package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private int idLaboratorio;
     private String nombreLaboratorio;
     private String descripcionLaboratorio;
     private String imagenLaboratoiol;
     private Byte habilitado;
     private int horarioIdHorario;

    public Laboratorio() {
    }

	
    public Laboratorio(int idLaboratorio, int horarioIdHorario) {
        this.idLaboratorio = idLaboratorio;
        this.horarioIdHorario = horarioIdHorario;
    }
    public Laboratorio(int idLaboratorio, String nombreLaboratorio, String descripcionLaboratorio, String imagenLaboratoiol, Byte habilitado, int horarioIdHorario) {
       this.idLaboratorio = idLaboratorio;
       this.nombreLaboratorio = nombreLaboratorio;
       this.descripcionLaboratorio = descripcionLaboratorio;
       this.imagenLaboratoiol = imagenLaboratoiol;
       this.habilitado = habilitado;
       this.horarioIdHorario = horarioIdHorario;
    }
   
    public int getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(int idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }
    public String getNombreLaboratorio() {
        return this.nombreLaboratorio;
    }
    
    public void setNombreLaboratorio(String nombreLaboratorio) {
        this.nombreLaboratorio = nombreLaboratorio;
    }
    public String getDescripcionLaboratorio() {
        return this.descripcionLaboratorio;
    }
    
    public void setDescripcionLaboratorio(String descripcionLaboratorio) {
        this.descripcionLaboratorio = descripcionLaboratorio;
    }
    public String getImagenLaboratoiol() {
        return this.imagenLaboratoiol;
    }
    
    public void setImagenLaboratoiol(String imagenLaboratoiol) {
        this.imagenLaboratoiol = imagenLaboratoiol;
    }
    public Byte getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Byte habilitado) {
        this.habilitado = habilitado;
    }
    public int getHorarioIdHorario() {
        return this.horarioIdHorario;
    }
    
    public void setHorarioIdHorario(int horarioIdHorario) {
        this.horarioIdHorario = horarioIdHorario;
    }




}


