package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {

     private int idRol;
     private String nombreRol;
     private int usuarioIdUsuario;

    public Rol() {
    }

	
    public Rol(int idRol, int usuarioIdUsuario) {
        this.idRol = idRol;
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public Rol(int idRol, String nombreRol, int usuarioIdUsuario) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.usuarioIdUsuario = usuarioIdUsuario;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public int getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(int usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }




}


