package model;
// Generated 1/10/2021 11:37:45 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String apellido;
     private String correo;
     private String contrasena;
     private Byte activo;
     private String imagenUsuario;
     private Integer semestre;
     private int grupoIdGrupo;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, int grupoIdGrupo) {
        this.idUsuario = idUsuario;
        this.grupoIdGrupo = grupoIdGrupo;
    }
    public Usuario(int idUsuario, String nombre, String apellido, String correo, String contrasena, Byte activo, String imagenUsuario, Integer semestre, int grupoIdGrupo) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.contrasena = contrasena;
       this.activo = activo;
       this.imagenUsuario = imagenUsuario;
       this.semestre = semestre;
       this.grupoIdGrupo = grupoIdGrupo;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(Byte activo) {
        this.activo = activo;
    }
    public String getImagenUsuario() {
        return this.imagenUsuario;
    }
    
    public void setImagenUsuario(String imagenUsuario) {
        this.imagenUsuario = imagenUsuario;
    }
    public Integer getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }
    public int getGrupoIdGrupo() {
        return this.grupoIdGrupo;
    }
    
    public void setGrupoIdGrupo(int grupoIdGrupo) {
        this.grupoIdGrupo = grupoIdGrupo;
    }


}


